##** MERGE**

1) **Merge**

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})
df2= pd.DataFrame({"A":[2,4,6,8],"B":["a","c","e","f"]})


# By default, pandas performs an inner merge on common columns (here, 'A' and 'B').
pd.merge(df1,df2)

   A  B
0  2  a
1  4  c

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})
df2= pd.DataFrame({"A":[2,4,6,8],"B":["a","c","e","f"]})
pd.merge(df1,df2)
df3=pd.merge(df1,df2)
print(df3)        # Display the merged DataFrame

   A  B
0  2  a
1  4  c

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})# Merges df1 and df2 on the common column 'A'.
 # It performs an inner merge by default, only keeping rows where 'A' values match in both
 # Columns 'B' and 'C' are included as they are unique to each DataFrame.
df2= pd.DataFrame({"A":[2,4,6,8],"C":["a","c","e","f"]})
pd.merge(df1,df2)

   A  B  C
0  2  a  a
1  4  c  c

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})
df2= pd.DataFrame({"A":[2,4,6,8],"B":["a","c","e","f"]})
pd.merge(df1,df2)
pd.merge(df1,df2, on ="A",how ="inner")

   A B_x B_y
0  2   a   a
1  4   c   c

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})
df2= pd.DataFrame({"A":[2,4,6,8],"B":["a","c","e","f"]})
pd.merge(df1,df2)
pd.merge(df1,df2, on ="A",how ="right")

   A  B_x B_y
0  2    a   a
1  4    c   c
2  6  NaN   e
3  8  NaN   f

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})
df2= pd.DataFrame({"A":[2,4,6,8],"B":["a","c","e","f"]})
pd.merge(df1,df2)
pd.merge(df1,df2, on ="A",how ="left")

   A B_x  B_y
0  2   a    a
1  3   b  NaN
2  4   c    c
3  5   d  NaN

In [ ]:

import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})
df2= pd.DataFrame({"A":[2,4,6,8],"B":["a","c","e","f"]})
pd.merge(df1,df2)
pd.merge(df1,df2, on ="A",how ="outer")

   A  B_x  B_y
0  2    a    a
1  3    b  NaN
2  4    c    c
3  5    d  NaN
4  6  NaN    e
5  8  NaN    f

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})
df2= pd.DataFrame({"A":[2,3,4,5],"B":["a","c","e","f"]})
pd.merge(df1,df2)

   A  B
0  2  a

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})
df2= pd.DataFrame({"A":[2,3,4,5],"B":["e","f","g","h"]})
pd.merge(df1,df2)

Empty DataFrame
Columns: [A, B]
Index: []

In [ ]:
import pandas as pd
v1= pd.DataFrame({"roll_no":[20,21,22,23],"name":["umang","sadaf","manu","kani"]})
v2= pd.DataFrame({"roll_no":[20,21,22,23],"marks":["60","70","80","88"]})
S= pd.merge(v1,v2)
print(s)

NameError: name 's' is not defined

In [ ]:
import pandas as pd
df1= pd.DataFrame({"roll_no":[20,21,22,23,24],"name":["umang","sadaf","manu","kani","naina"]})
df2= pd.DataFrame({"roll_no":[20,21,22,23,24],"marks":["60","70","80","88","99"]})
SI= pd.merge(df1,df2)
print(SI)

   roll_no   name marks
0       20  umang    60
1       21  sadaf    70
2       22   manu    80
3       23   kani    88
4       24  naina    99

In [ ]:
import pandas as pd
df1= pd.DataFrame({"roll_no":[20,21,25,23,24],"name":["umang","sadaf","manu","kani","naina"]})
df2= pd.DataFrame({"roll_no":[20,21,22,23,26],"marks":["60","70","80","88","99"]})
SI= pd.merge(df1,df2,how="inner")
print(SI)

   roll_no   name marks
0       20  umang    60
1       21  sadaf    70
2       23   kani    88

In [ ]:
import pandas as pd
df1= pd.DataFrame({"roll_no":[20,21,28,23,24],"name":["umang","sadaf","manu","kani","naina"]})
df2= pd.DataFrame({"roll_no":[20,21,22,23,29],"marks":["60","70","80","88","99"]})
SI= pd.merge(df1,df2,how="outer")
print(SI)

   roll_no   name marks
0       20  umang    60
1       21  sadaf    70
2       22    NaN    80
3       23   kani    88
4       24  naina   NaN
5       28   manu   NaN
6       29    NaN    99

In [ ]:
import pandas as pd
df1= pd.DataFrame({"roll_no":[20,21,67,23,24],"name":["umang","sadaf","manu","kani","naina"]})
df2= pd.DataFrame({"roll_no":[20,21,22,34,24],"marks":["60","70","80","88","99"]})
SI= pd.merge(df1,df2,how="left")
print(SI)

   roll_no   name marks
0       20  umang    60
1       21  sadaf    70
2       67   manu   NaN
3       23   kani   NaN
4       24  naina    99

In [ ]:
import pandas as pd
df1= pd.DataFrame({"roll_no":[20,21,58,23,24],"name":["umang","sadaf","manu","kani","naina"]})
df2= pd.DataFrame({"roll_no":[20,21,89,23,24],"marks":["60","70","80","88","99"]})
SI= pd.merge(df1,df2,how="right")
print(SI)

   roll_no   name marks
0       20  umang    60
1       21  sadaf    70
2       89    NaN    80
3       23   kani    88
4       24  naina    99

In [ ]:
import pandas as pd
df1= pd.DataFrame({"roll_no":[20,21,28,23,24],"name":["umang","sadaf","manu","kani","naina"]})
df2= pd.DataFrame({"roll_no":[20,21,22,23,29],"marks":["60","70","80","88","99"]})
SI= pd.merge(df1,df2,how="outer",indicator="True")
print(SI)

   roll_no   name marks        True
0       20  umang    60        both
1       21  sadaf    70        both
2       22    NaN    80  right_only
3       23   kani    88        both
4       24  naina   NaN   left_only
5       28   manu   NaN   left_only
6       29    NaN    99  right_only

In [ ]:
import pandas as pd
df1= pd.DataFrame({"roll_no":[20,21,28,23,24],"name":["umang","sadaf","manu","kani","naina"]})
df2= pd.DataFrame({"roll_no":[20,21,22,23,29],"name":["umang","sadaf","manu","kani","priya"]})
SI= pd.merge(df1,df2,how="outer")
print(SI)

   roll_no   name
0       20  umang
1       21  sadaf
2       22   manu
3       23   kani
4       24  naina
5       28   manu
6       29  priya

In [ ]:
import pandas as pd
df1= pd.DataFrame({"roll_no":[20,21,28,23,24],"name":["umang","sadaf","manu","kani","naina"]})
df2= pd.DataFrame({"roll_no":[20,21,22,23,29],"name":["umang","sadaf","manu","kani","priya"]})
SI= pd.merge(df1,df2,right_index= True,left_index= True)
print(SI)

   roll_no_x name_x  roll_no_y name_y
0         20  umang         20  umang
1         21  sadaf         21  sadaf
2         28   manu         22   manu
3         23   kani         23   kani
4         24  naina         29  priya

In [ ]:
import pandas as pd
df1= pd.DataFrame({"roll_no":[20,21,22,23,24],"name":["umang","sadaf","manu","kani","naina"]})
df2= pd.DataFrame({"roll_no":[20,21,22,23,24],"marks":["60","70","80","88","99"]})
SI= pd.merge(df1,df2,right_index= True,left_index= True,suffixes=('9th','10th'))
print(SI)

   roll_no9th   name  roll_no10th marks
0          20  umang           20    60
1          21  sadaf           21    70
2          22   manu           22    80
3          23   kani           23    88
4          24  naina           24    99

##**JOIN**

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})
df2= pd.DataFrame({"D":[2,4,6,8],"C":["a","c","e","f"]})
df1.join(df2)

   A  B  D  C
0  2  a  2  a
1  3  b  4  c
2  4  c  6  e
3  5  d  8  f

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]},index=["a","b","c","d"])
df2= pd.DataFrame({"C":[2,4,6,8],"D":["a","c","e","f"]})
df1.join(df2)

   A  B   C    D
a  2  a NaN  NaN
b  3  b NaN  NaN
c  4  c NaN  NaN
d  5  d NaN  NaN

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]},index=[1,2,3,4])
df2= pd.DataFrame({"C":[2,4,6,8],"D":["a","c","e","f"]})
df1.join(df2)

   A  B    C    D
1  2  a  4.0    c
2  3  b  6.0    e
3  4  c  8.0    f
4  5  d  NaN  NaN

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]},index=["a","b","c","d"])
df2= pd.DataFrame({"C":[2,4],"D":["a","c"]},index=["a","b"])
df1.join(df2)

   A  B    C    D
a  2  a  2.0    a
b  3  b  4.0    c
c  4  c  NaN  NaN
d  5  d  NaN  NaN

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]},index=["a","b","c","d"])
df2= pd.DataFrame({"C":[2,4],"D":["a","c"]},index=["a","b"])
df2.join(df1)

   C  D  A  B
a  2  a  2  a
b  4  c  3  b

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]},index=["a","b","c","d"])
df2= pd.DataFrame({"C":[2,4],"D":["a","c"]},index=["a","b"])
df1.join(df2,how="inner")

   A  B  C  D
a  2  a  2  a
b  3  b  4  c

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]},index=["a","b","c","d"])
df2= pd.DataFrame({"C":[2,4],"D":["a","c"]},index=["a","b"])
df1.join(df2,how="outer")

   A  B    C    D
a  2  a  2.0    a
b  3  b  4.0    c
c  4  c  NaN  NaN
d  5  d  NaN  NaN

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]},index=["a","b","c","d"])
df2= pd.DataFrame({"C":[2,4],"D":["a","c"]},index=["a","b"])
df1.join(df2,how="left")

   A  B    C    D
a  2  a  2.0    a
b  3  b  4.0    c
c  4  c  NaN  NaN
d  5  d  NaN  NaN

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]},index=["a","b","c","d"])
df2= pd.DataFrame({"C":[2,4],"D":["a","c"]},index=["a","b"])
df1.join(df2,how="right")

   A  B  C  D
a  2  a  2  a
b  3  b  4  c

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]},index=["a","b","c","d"])
df2= pd.DataFrame({"A":[2,4],"C":["a","c"]},index=["a","b"])
df1.join(df2,lsuffix="_left")

   A_left  B    A    C
a       2  a  2.0    a
b       3  b  4.0    c
c       4  c  NaN  NaN
d       5  d  NaN  NaN

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]},index=["a","b","c","d"])
df2= pd.DataFrame({"A":[2,4],"C":["a","c"]},index=["a","b"])
df1.join(df2,rsuffix="_right")

   A  B  A_right    C
a  2  a      2.0    a
b  3  b      4.0    c
c  4  c      NaN  NaN
d  5  d      NaN  NaN

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})
df2= pd.DataFrame({"C":[2,4,6,8],"D":["a","c","e","f"]})
df3= pd.DataFrame({"E":[2,4,6,8],"F":["a","c","e","f"]})
df1.join([df2,df3])

   A  B  C  D  E  F
0  2  a  2  a  2  a
1  3  b  4  c  4  c
2  4  c  6  e  6  e
3  5  d  8  f  8  f

In [ ]:
import pandas as pd
df1= pd.DataFrame({"A":[2,3,4,5],"B":["a","b","c","d"]})
df2= pd.DataFrame({"C":[2,4,6,8],"D":["a","c","e","f"]})
df3= pd.DataFrame({"E":[2,4,6,8],"F":["a","c","e","f"]})
df1.join(df2).join(df3)

   A  B  C  D  E  F
0  2  a  2  a  2  a
1  3  b  4  c  4  c
2  4  c  6  e  6  e
3  5  d  8  f  8  f

#**concat**

In [ ]:
import pandas as pd
roll_no =pd.Series([1,2,3,4])
roll_no2=pd.Series([20,30,40,50])
pd.concat([roll_no,roll_no2])

0     1
1     2
2     3
3     4
0    20
1    30
2    40
3    50
dtype: int64

In [ ]:
import pandas as pd
roll_no =pd.Series([1,2,3,4])
roll_no2=pd.Series([20,30,40,50])
pd.concat([roll_no,roll_no2],axis=0)               #axis=0

0     1
1     2
2     3
3     4
0    20
1    30
2    40
3    50
dtype: int64

In [ ]:
import pandas as pd
roll_no =pd.Series([1,2,3,4])
roll_no2=pd.Series([20,30,40,50])
pd.concat([roll_no,roll_no2],axis=1)        #use axis =1

   0   1
0  1  20
1  2  30
2  3  40
3  4  50

In [ ]:
import pandas as pd
roll_no =pd.Series([1,2,3,4])
roll_no2=pd.Series([20,30,40,50])
pd.concat([roll_no,roll_no2],axis=0,ignore_index=True)       #use ignor_index to ignor index value

0     1
1     2
2     3
3     4
4    20
5    30
6    40
7    50
dtype: int64

In [ ]:
import pandas as pd
roll_no =pd.Series([1,2,3,4])
roll_no2=pd.Series([20,30,40,50])
pd.concat([roll_no,roll_no2],axis=0,ignore_index=False)   #dont ignor index value

0     1
1     2
2     3
3     4
0    20
1    30
2    40
3    50
dtype: int64

In [ ]:
df1=pd.DataFrame({"A":[1,2,3],"B":["a","b","c"]})
df2=pd.DataFrame({"A":[2,4,6],"B":["a","c","e"]})
pd.concat([df1,df2])

   A  B
0  1  a
1  2  b
2  3  c
0  2  a
1  4  c
2  6  e

In [ ]:
df1=pd.DataFrame({"A":[1,2,3],"B":["a","b","c"]})
df2=pd.DataFrame({"A":[2,4,6],"B":["a","c","e"]})
pd.concat([df1,df2],axis=1)

   A  B  A  B
0  1  a  2  a
1  2  b  4  c
2  3  c  6  e

we do not use left and right but use inner or outer

In [ ]:
df1=pd.DataFrame({"A":[1,2,3],"B":["a","b","c"]})
df2=pd.DataFrame({"A":[2,4,6],"B":["a","c","e"]})
pd.concat([df1,df2],join="inner")

   A  B
0  1  a
1  2  b
2  3  c
0  2  a
1  4  c
2  6  e

In [ ]:
df1=pd.DataFrame({"A":[1,2,3],"B":["a","b","c"]})
df2=pd.DataFrame({"A":[2,4,6],"B":["a","c","e"]})
pd.concat([df1,df2],join="outer")

   A  B
0  1  a
1  2  b
2  3  c
0  2  a
1  4  c
2  6  e

In [ ]:
df1=pd.DataFrame({"A":[1,2,3],"B":["a","b","c"]})
df2=pd.DataFrame({"A":[2,4,6],"B":["a","c","e"]})
pd.concat([df1,df2],join="right")         #use for checking error

ValueError: Only can inner (intersect) or outer (union) join the other axis

In [ ]:
df1=pd.DataFrame({"A":[1,2,3],"B":["a","b","c"]})
df2=pd.DataFrame({"A":[2,4,6],"B":["a","c","e"]})
pd.concat([df1,df2],join="left")     #use for error

ValueError: Only can inner (intersect) or outer (union) join the other axis

In [ ]:
df1=pd.DataFrame({"A":[1,2,3],"B":["a","b","c"]})
df2=pd.DataFrame({"A":[2,4,6],"B":["a","c","e"]})
pd.concat([df1,df2],axis=1,keys=["umang","kanishka"])

  umang    kanishka
      A  B        A  B
0     1  a        2  a
1     2  b        4  c
2     3  c        6  e

In [ ]:
df1=pd.DataFrame({"A":[1,2,3],"B":["a","b","c"]})
df2=pd.DataFrame({"A":[2,4,6],"B":["a","c","e"]})
pd.concat([df1,df2],axis=0,keys=["umang","kanishka"])

            A  B
umang    0  1  a
         1  2  b
         2  3  c
kanishka 0  2  a
         1  4  c
         2  6  e

In [ ]:
df1=pd.DataFrame({"A":[1,2,3]})         #remove one column
df2=pd.DataFrame({"A":[2,4,6],"B":["a","c","e"]})
pd.concat([df1,df2],axis=1)

   A  A  B
0  1  2  a
1  2  4  c
2  3  6  e

In [ ]:
#length change
d1=pd.DataFrame({"A":[1,2,3],"B":["a","b","c"]})
df2=pd.DataFrame({"A":[2,4],"B":["a","c"]})
pd.concat([df1,df2],axis=1)

   A    A    B
0  1  2.0    a
1  2  4.0    c
2  3  NaN  NaN