##
**Data Manipulation with panda**

## 1)series

Write a Python program using Pandas to create a Series from the given marks [2, 4, 6, 8, 10] and customize its index as a, b, c, d, e. Also display the type of the Series.

In [ ]:

import pandas as pd
marks=[2,4,6,8,10]
DS=pd.Series(marks)
print(type(DS))

<class 'pandas.core.series.Series'>

In [ ]:
#customize index
import pandas as pd
marks=[2,4,6,8,10]
DS=pd.Series(marks,index=["a","b","c","d","e"])
print(DS)

a     2
b     4
c     6
d     8
e    10
dtype: int64

Write a Python program using Pandas to create a Series from the marks [2, 4, 6, 8, 10] and assign custom indexes ["a", "b", "c", "d", "e"]. Display the Series.

In [9]:
#value error
import pandas as pd
marks=[2,4,6,8,10]
DS=pd.Series(marks,index=["a","b","c","d"])     # it will give error if the lenght is not same
print(DS)

ValueError: Length of values (5) does not match length of index (4)

In [ ]:
import pandas as pd
marks=[2,4,6,8,10]
DS=pd.Series(marks,index=["a","b","c","d","e","f"])       # it will give errpr if the length value is not same
print(DS)

ValueError: Length of values (5) does not match length of index (6)

Write a Python program using Pandas to create a Series from the marks [2, 4, 6, 8, 10] with custom index labels ["a", "b", "c", "d", "e"], convert the data type to float, and assign a name to the Series. Then display the Series.

In [14]:
#convert datatype
import pandas as pd
marks=[2,4,6,8,10]
DS=pd.Series(marks,index=["a","b","c","d","e"],dtype="float",name="marksheet record")
print(DS)

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
Name: marksheet record, dtype: float64

1.1)  common operation

Write a Python program using Pandas to perform common operations on a Series and find its sum, minimum, maximum, and mean.

In [16]:
#common method in series
print(DS.sum())
print(f"minimum number in series: ",DS.min())
print(f"maximum number of series: ",DS.max())
print(f"mean number of series: ", DS.mean())

30.0
minimum number in series:  2.0
maximum number of series:  10.0
mean number of series:  6.0

1.2) indexing and slicing

Write a Python program using Pandas to access an element of a Series using its integer position.

In [17]:
# using indexing
print(f"access elemet by int",{DS[1]})

access elemet by int {np.float64(4.0)}

/tmp/ipykernel_743/3182128965.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"access elemet by int",{DS[1]})

Write a Python program to access an element of a Pandas Series using its index label.

In [ ]:
#indexing and slicing
print("access elemet by int",DS["a"])

Write a Python program to perform slicing on a Pandas Series and display the first three elements.

In [ ]:
#using slicing
print("slicing in series",DS[0:3])

slicing in series a    2.0
b    4.0
c    6.0
Name: marksheet record, dtype: float64

1.3) vectorized operation

Write a Python program using Pandas to perform vectorized operations on a Series by multiplying all its elements by 3.

In [19]:
#multiply 2 by every value
DS*3

a     6.0
b    12.0
c    18.0
d    24.0
e    30.0
Name: marksheet record, dtype: float64

Write a Python program using Pandas to perform vectorized operations on a Series by adding all its elements by 2

In [20]:
#add 2 by every value
DS+2

a     4.0
b     6.0
c     8.0
d    10.0
e    12.0
Name: marksheet record, dtype: float64

Write a Python program using Pandas to perform subtraction on all elements of a Series by subtracting 5 from each value.

In [21]:
#subtract 5 bt every value
DS - 5

a   -3.0
b   -1.0
c    1.0
d    3.0
e    5.0
Name: marksheet record, dtype: float64

Write a Python program using Pandas to perform Division on all elements of a Series

In [22]:
DS/2

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: marksheet record, dtype: float64

Write a Python program using Pandas to perform exponentiation on a Series by raising each element to the power of 2.

In [23]:
DS**2

a      4.0
b     16.0
c     36.0
d     64.0
e    100.0
Name: marksheet record, dtype: float64

Write a Python program using Pandas to find the remainder when each element of a Series is divided by 5.

In [24]:
DS%5

a    2.0
b    4.0
c    1.0
d    3.0
e    0.0
Name: marksheet record, dtype: float64

Create a Pandas Series from a dictionary containing a student's name, age, and marks, and then access and display the student's name from the Series.

In [ ]:
info={
    "name":"umang",
    "age":21,
    "marks":[20,30,54]
}
DS1= pd.Series(info)
DS1["name"]

'umang'

Create a Pandas Series with a single value 5 and display it.

In [ ]:
# creat a digit with single number
num=pd.Series(5)
print(num)

0    5
dtype: int64

Create a Pandas Series with a single value 5 and assign the custom index labels [1, 2, 3, 4, 5]. Then display the Series.

In [ ]:
#using index
num=pd.Series(5,index=[1,2,3,4,5])
print(num)

1    5
2    5
3    5
4    5
5    5
dtype: int64

Create two Pandas Series with the same index [1, 2, 3, 4, 5], containing values 5 and 10, and add them together.

In [ ]:
num=pd.Series(5,index=[1,2,3,4,5])
num1=pd.Series(10,index=[1,2,3,4,5])
print(num+num1)

1    15
2    15
3    15
4    15
5    15
dtype: int64

Create two Pandas Series with different index labels—[1,2,3,4,5] and ["a","b","c","d","e"]—and add them together. Observe the result when the indexes do not match.

In [ ]:
num=pd.Series(5,index=[1,2,3,4,5])
num1=pd.Series(10,index=[0,5,10,18,20])
print(num+num1)

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5     15.0
10     NaN
18     NaN
20     NaN
dtype: float64

##
**DATA FRAME**

2.1) DataFrame

Create a Pandas DataFrame using a dictionary containing students' names, roll numbers, and marks, and display the DataFrame.

In [ ]:
import pandas as pd
student={
    "name":["umang","kani","sadaf"],
    "roll_no":[100,200,300],
    "marks":[80,81,88]
}
df=pd.DataFrame(student)
print(df)

    name  roll_no  marks
0  umang      100     80
1   kani      200     81
2  sadaf      300     88

Create a Pandas DataFrame using a dictionary containing students' names, roll numbers, and marks, and display the DataFrame.

In [ ]:
#length error
import pandas as pd
student={
    "name":["umang","kani","sadaf"],
    "roll_no":[100,300],
    "marks":[80,81,88]                          #Length of the value is not value same
}
df=pd.DataFrame(student)
print(df)

ValueError: All arrays must be of the same length

Create a Pandas DataFrame using a list of lists, where the first list contains student names and the second list contains their marks. Display the DataFrame.

In [ ]:
#CREATING A DATARAME WITH LIST
students_info = [["a","b","c"],[20,40,60]]
pd.DataFrame(students_info)

    0   1   2
0   a   b   c
1  20  40  60

Create a Pandas DataFrame using Pandas Series and display the DataFrame.

In [ ]:
students_info = [["a","b","c"],[20,40,60]]
pd.DataFrame(students_info)
print(df) #df with print

    name  roll_no  marks
0  umang      100     80
1   kani      200     81
2  sadaf      300     88

Create a Pandas DataFrame using two Pandas Series: one containing student names and the other containing their roll numbers. Then display the DataFrame.

In [ ]:
Sr= {
    "name":pd.Series(["umang","kani","sadaf","naina","manu"]),
    "rll": pd.Series([100,200,300,400,500])
   }
df = pd.DataFrame(Sr)
df

    name  rll
0  umang  100
1   kani  200
2  sadaf  300
3  naina  400
4   manu  500

2.1)arithmetic operatin in dataframe

Create a Pandas DataFrame with two columns a and b containing the given values, and display the DataFrame

In [ ]:
var = pd.DataFrame({"a":[1,2,3,4],"b":[5,6,7,8]})
var

   a  b
0  1  5
1  2  6
2  3  7
3  4  8

Create a Pandas DataFrame with columns a and b, then create a new column c by adding the values of columns a and b. Display the updated DataFrame.

In [ ]:
var = pd.DataFrame({"a":[1,2,3,4],"b":[5,6,7,8]})
var['c']=var['a']+ var['b']
var

   a  b   c
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

#filtering

Create a DataFrame with columns a and b, calculate a new column c by adding them, and create a Boolean column python that checks whether c > 10.

In [ ]:
var = pd.DataFrame({"a":[1,2,3,4],"b":[5,6,7,8]})
var['c']=var['a']+ var['b']
var["python"]= var['c']>10
var

   a  b   c  python
0  1  5   6   False
1  2  6   8   False
2  3  7  10   False
3  4  8  12    True

Create a DataFrame with columns a and b, calculate column c as their sum, and create a Boolean column python that checks whether c >= 10.

In [25]:
var = pd.DataFrame({'a':[1,2,3,4],'b':[5,6,7,8]})
var['c'] = var["a"] + var["b"]
var["python"] = var["c"] >= 10
var

   a  b   c  python
0  1  5   6   False
1  2  6   8   False
2  3  7  10    True
3  4  8  12    True

##  handling missing value

Create a student DataFrame using a dictionary containing name, roll number, marks, subject, and city, with some missing values represented by np.nan, and display the DataFrame.

In [ ]:
import numpy as np
stu_info= {
    "name":["umang","kani","sadaf",np.nan,"manu"],

    "roll_no":[100,300,np.nan,500,600],
    "marks":[80,81,88,np.nan,90],
    "subject":["hindi","eng",np.nan,"math",np.nan],
    "city":["deh","bijnor","meerut",np.nan,"hapur"]
}
df

    name  rll
0  umang  100
1   kani  200
2  sadaf  300
3  naina  400
4   manu  500

Create a Pandas DataFrame containing student details with some missing values represented by np.nan. Then use df.info() to display the DataFrame’s column names, non-null counts, data types, and memory usage.

In [ ]:
import numpy as np
stu_info= {
    "name":["umang","kani","sadaf",np.nan,"manu"],

    "roll_no":[100,300,np.nan,500,600],
    "marks":[80,81,88,np.nan,90],
    "subject":["hindi","eng",np.nan,"math",np.nan],
    "city":["deh","bijnor","meerut",np.nan,"hapur"]
}
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   rll     5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

Create a student DataFrame containing missing values using np.nan, then use df.isnull().sum().sum() to find the total number of missing values in the DataFrame.

In [ ]:
import numpy as np
stu_info= {
    "name":["umang","kani","sadaf",np.nan,"manu"],

    "roll_no":[100,300,np.nan,500,600],
    "marks":[80,81,88,np.nan,90],
    "subject":["hindi","eng",np.nan,"math",np.nan],
    "city":["deh","bijnor","meerut",np.nan,"hapur"]
}
df.isnull()

    name    rll
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False

In [ ]:
import numpy as np
stu_info= {
    "name":["umang","kani","sadaf",np.nan,"manu"],

    "roll_no":[100,300,np.nan,500,600],
    "marks":[80,81,88,np.nan,90],
    "subject":["hindi","eng",np.nan,"math",np.nan],
    "city":["deh","bijnor","meerut",np.nan,"hapur"]
}
print(df.isnull().sum().sum())

0

Create a DataFrame containing missing (NaN) values and use the dropna() function to remove all rows that contain at least one missing value. Display the resulting DataFrame.

In [ ]:
#remove null value
df.dropna()

    name  rll
0  umang  100
1   kani  200
2  sadaf  300
3  naina  400
4   manu  500

Create a Pandas DataFrame with missing values and use dropna(subset=["marks"]) to remove only those rows where the marks column contains a missing value. Display the resulting DataFrame.

In [26]:
import numpy as np
import pandas as pd

std = {
    "name": ["kanishka", "umang", "sadaf", "kunal", "naina"],
    "roll_no.": [10, 11, 12, 15, np.nan],
    "marks": [20, np.nan, 30, 60, 50],
    "subject": ["hindi", "english", np.nan, "maths", "physics"],
    "city": ["delhi", np.nan, "bijnor", "muzaffarnaar", "chandigarh"],
}

df = pd.DataFrame(std)

# Drop rows where the 'marks' column has missing values
df = df.dropna(subset=["marks"])

print(df)

       name  roll_no.  marks  subject          city
0  kanishka      10.0   20.0    hindi         delhi
2     sadaf      12.0   30.0      NaN        bijnor
3     kunal      15.0   60.0    maths  muzaffarnaar
4     naina       NaN   50.0  physics    chandigarh

Write a Pandas program to replace missing values in the name column with "unknown name" using fillna(), and display the DataFrame.

In [27]:
df["name"] = df["name"].fillna("unknown name")
print(df)

       name  roll_no.  marks  subject          city
0  kanishka      10.0   20.0    hindi         delhi
2     sadaf      12.0   30.0      NaN        bijnor
3     kunal      15.0   60.0    maths  muzaffarnaar
4     naina       NaN   50.0  physics    chandigarh